---
title: "Course Notes"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Course Notes}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This page contains the list of links pointing to the different chapters in the course notes. 

```{r, echo=FALSE, message=FALSE, warning=FALSE}
s_cn_url <- "https://charlotte-ngs.github.io/asmss2023/cn/"
tbl_chpt <- tibble::tibble(Nr      = c(1, 2, 3, 4, 5, 6),
                           Date    = c(rep("2023-02-20",2),
                                       "2023-03-06",
                                       "2023-03-20",
                                       "2023-04-03",
                                       "2023-04-24"),
                           Topic   = c(
                             paste0("[Introducion](", s_cn_url, "01_intro.pdf)", collapse = ""),
                             paste0("[Linear Regression](", s_cn_url, "02_regr.pdf)", collapse = ""),
                             paste0("[Fixed Linear Effects Models](", s_cn_url, "03_flem.pdf)", collapse = ""),
                             paste0("[Contrasts](", s_cn_url, "035_contrasts.pdf)", collapse = ""),
                             paste0("[Interactions](", s_cn_url, "036_interactions.pdf)", collapse = ""),
                             paste0("[Mixed Linear Effects Models](", s_cn_url, "04_mlem.pdf)", collapse = "")
                             ))
knitr::kable(tbl_chpt)
```

