---
title: "Additional Material"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Additional Material}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This page contains additional material like links to slides, video recordings, ohp pictures, and more ...

```{r cam-setup, echo=FALSE}
s_root_url <- "https://charlotte-ngs.github.io/asmss2023/"
```


## Slides

```{r tbl-sl, echo=FALSE, message=FALSE, warning=FALSE}
s_sl_url <- paste(s_root_url, "sl/", sep = "")
tbl_sl <- tibble::tibble(Nr = c(1, 2, 3, 4, 5, 6, 7),
                         Date = c(rep("2023-02-20",2),
                                  "2023-03-06",
                                  "2023-03-13",
                                  "2023-03-27",
                                  "2023-04-03",
                                  "2023-04-17"),
                         Topic = c(
                           paste0("[Introduction](", s_sl_url, "asm-w01-v01-intro.pdf)", collapse = ""),
                           paste0("[Linear Regression](", s_sl_url, "l02_regr.pdf)", collapse = ""),
                           paste0("[Fixed Linear Effects Model](", s_sl_url, "l03_flem.pdf)", collapse = ""),
                           paste0("[Regression on Dummy Variables](", s_sl_url, "l04_regdvar.pdf)", collapse = ""),
                           paste0("[Contrasts](", s_sl_url, "l05_contrasts.pdf)", collapse = ""),
                           paste0("[Interactions](", s_sl_url, "l06_interactions.pdf)", collapse = ""),
                           paste0("[Simulation](", s_sl_url, "l07_simulation.pdf)", collapse = "")
                         ))
                                  
knitr::kable(tbl_sl)
```


## Slides with Notes

```{r tbl-sl-notes, echo=FALSE, message=FALSE, warning=FALSE}
s_sl_notes_url <- paste(s_root_url,"sl_notes/", sep = "")
tbl_sl_notes <- tibble::tibble(Nr = c(1, 2),
                               Date = c(rep("2023-04-17", 2)),
                               Topic = c(
                                 paste0("[Interactions](", s_sl_notes_url, "l06_interactions_with_notes.pdf)", collapse = ""),
                                 paste0("[Simulation](", s_sl_notes_url, "l07_simulation_with_notes.pdf)", collapse = "")
                               ))
```



## OHP Pictures

```{r tbl-ohp, echo=FALSE, message=FALSE, warning=FALSE}
s_ohp_url <- "https://charlotte-ngs.github.io/asmss2023/ohp/"
tbl_ohp <- tibble::tibble(Nr = c(1, 2, 3, 4, 5, 6),
                          Date = c("2023-02-20",
                                   "2023-02-27",
                                   "2023-03-06",
                                   "2023-03-13",
                                   "2023-03-20",
                                   "2023-03-27"),
                          Topic = c(
                            paste0("[Introduction](", s_ohp_url, "20230220_ohp_l01.pdf)", collapse = ""),
                            paste0("[Linear Regression](", s_ohp_url, "20230227_ohp_l02.pdf)", collapse = ""),
                            paste0("[Fixed Linear Effects Model](", s_ohp_url, "20230306_ohp_l03.pdf)", collapse = ""),
                            paste0("[Regression on Dummy Variables](", s_ohp_url, "20230313_ohp_l04.pdf)", collapse = ""),
                            paste0("[Estimable Functions](", s_ohp_url, "20230320_ohp_l05.pdf)", collapse = ""),
                            paste0("[Contrasts](", s_ohp_url, "20230327_ohp_l06.pdf)", collapse = "")
                            ))
knitr::kable(tbl_ohp)
```


## Video

```{r tbl-video, echo=FALSE, message=FALSE, warning=FALSE}
tbl_video <- tibble::tibble(Nr = c(1, 2, 3, 4, 5, 6, 7, 8),
                            Date = c("2023-02-20",
                                     "2023-02-27",
                                     "2023-03-06",
                                     "2023-03-13",
                                     "2023-03-20",
                                     "2023-03-27",
                                     "2023-04-03",
                                     "2023-04-17"),
                            Topic = c("[Introduction](https://youtu.be/_1NiimKYyNQ)",
                                      "[Linear Regression](https://youtu.be/fnEsBNTM0Mk)",
                                      "[Multiple Linear Regression](https://youtu.be/A8n8o_Clw1s)",
                                      "[Regression on Dummy Variables](https://youtu.be/3PAOjpUwH4I)",
                                      "[Estimable Functions and Contrasts](https://youtu.be/8E4-q9DMNWQ)",
                                      "[Contrasts](https://youtu.be/aL-C0h2ZUZY)",
                                      "[Contrasts II](https://youtu.be/Iqt3mJ06JNs)",
                                      "[Interactions and Simulation](https://youtu.be/7J69ZZhZjXc)"
                                      ))
knitr::kable(tbl_video)
```

