---
title: "Solutions"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Solutions}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This page contains solutions to exercises.

```{r, echo=FALSE, results='asis'}
s_url_sol <- "https://charlotte-ngs.github.io/asmss2023/sol/"
tbl_sol <- tibble::tibble(Nr = c(1, 2, 3, 4, 5, 6, 7, 8),
                         Date = c("2023-02-27",
                                  "2023-03-06",
                                  "2023-03-20",
                                  "2023-04-03",
                                  "2023-04-24",
                                  rep("2023-05-15", 3)),
                         Topic = c(
                           paste0("[Linear Regression](", s_url_sol, "asm_ex01_sol.pdf)",  collapse = ""),
                           paste0("[Linear Regression (Part 2)](", s_url_sol, "asm_ex02_sol.pdf)",  collapse = ""),
                           paste0("[Fixed Linear Effects Models](", s_url_sol, "asm_ex03_sol.pdf)", collapse = ""),
                           paste0("[Contrasts](", s_url_sol, "asm_ex04_sol.pdf)", collapse = ""),
                           paste0("[Interactions](", s_url_sol, "asm_ex05_sol.pdf)", collapse = ""),
                           paste0("[Pedigree BLUP](", s_url_sol, "asm_ex06_sol.pdf)", collapse = ""),
                           paste0("[Genomic BLUP](", s_url_sol, "asm_ex07_sol.pdf)", collapse = ""),
                           paste0("[Test Exam](", s_url_sol, "asm_exam_sol.pdf)", collapse = "")
                         ))
knitr::kable(tbl_sol)
```

